<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\csharp\Nvidia.Ovrtx\Nvidia.Ovrtx.csproj" />
  </ItemGroup>

  <!-- Fetch ovrtx native library -->
  <Import Project="..\msbuild\ovrtx.targets" />

</Project>
